[tool.pyright]
include = ["brewblox_devcon_spark"]
exclude = ["**/node_modules", "**/__pycache__"]
useLibraryCodeForTypes = true
reportMissingImports = "information"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
addopts = """
    --ignore=brewblox_devcon_spark/codec/proto-compiled/
    --cov=brewblox_devcon_spark
    --cov-branch
    --cov-report=term-missing:skip-covered
    --cov-fail-under=100
    --no-cov-on-fail
    --durations=3
    --timeout=10
    --timeout_method="signal"
    """

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "except asyncio.CancelledError:",
]

[tool.coverage.run]
omit = [
    "brewblox_devcon_spark/ymodem.py",
    "brewblox_devcon_spark/codec/proto-compiled/*",
]

[tool.ruff]
line-length = 120
exclude = [
    "brewblox_devcon_spark/codec/proto-compiled"
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D211",
    "D203",
    "D213",
    "COM812",
    "ISC001",
    "Q000",
    "Q003",
]

[tool.ruff.format]
indent-style = "space"
line-ending = "lf"
quote-style = "single"

[tool.ruff.lint.extend-per-file-ignores]
"test/**/*.py" = [
    # at least this three should be fine in tests:
    "S101", # asserts allowed in tests...
    "ARG", # Unused function args -> fixtures nevertheless are functionally relevant...
    "FBT", # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    # The below are debateable
    "PLR2004", # Magic value used in comparison, ...
    "S311", # Standard pseudo-random generators are not suitable for cryptographic purposes
    "D103", # Missing docstring in public function
    "ANN201", # Missing return type annotation
    "SLF001", # private member accessed
]

[project]
name = "brewblox-devcon-spark"
version = "1.0.0"
description = "Communication with Spark controllers"
readme = "README.md"
authors = [
    {name = "BrewPi", email = "development@brewpi.com"},
]
license = {text = "GPL-3.0"}
requires-python = "<4,>=3.11"
dependencies = [
    "protobuf<5",
    "aiofiles<24.0.0,>=23.2.1",
    "aiozeroconf<1.0.0,>=0.1.8",
    "debugpy<2.0.0,>=1.5.1",
    "Pint<1.0,>=0.22",
    "flexparser<1.0.0,<0.4",
    "pytimeparse<2.0.0,>=1.1.8",
    "ciso8601<3.0.0,>=2.2.0",
    "fastapi<0.110.0,>=0.104.1",
    "uvloop==0.20.0",
    "uvicorn[standard]==0.31.1",
    "httpx<1.0.0,>=0.25.2",
    "fastapi-mqtt<3.0.0,>=2.0.0",
    "pydantic-settings<3.0.0,>=2.1.0",
    "websockets<13.0,>=12.0",
    "httpx-ws<1.0.0,>=0.4.3",
    "dnspython<3.0.0,>=2.4.2",
    "bidict<1.0.0,>=0.23.1",
    "cryptography==42.0.8",
]
[dependency-groups]
dev = [
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "ruff",
    "invoke",
    "grpcio-tools<2.0.0,>=1.58.0",
    "pytest-docker",
    "pytest-asyncio>=0.24",
    "pytest-httpx",
    "asgi-lifespan",
    "pytest-timeout>=2.3.1",
]
[tool.astral_uv]
require-wheels = true
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
