import os
from configparser import ConfigParser
from contextlib import suppress
from pathlib import Path

from invoke import Context, task
from invoke.exceptions import Exit, UnexpectedExit

from brewblox_devcon_spark.models import FirmwareConfig

ROOT = Path(__file__).parent.resolve()
FW_BASE_URL = 'https://brewblox.blob.core.windows.net/firmware'
FW_RELEASE_FILE = 'brewblox-release.tar.gz'

# Default location of a local brewblox-firmware checkout.
# Used by the fetch-* tasks, and overruled by $BREWBLOX_FIRMWARE_REPO or --repo.
FW_LOCAL_REPO = ROOT.parent / 'firmware'

# Location of the brewblox-proto submodule inside a brewblox-firmware checkout
FW_PROTO_SUBMODULE = 'external_libs/brewblox-proto'


def get_fw_config() -> FirmwareConfig:  # pragma: no cover
    """
    Globally cached getter for firmware config.
    When first called, config is parsed from the firmware.ini file.
    """
    parser = ConfigParser()
    parser.read(ROOT / 'firmware.ini')
    raw = dict(parser['FIRMWARE'].items())
    config = FirmwareConfig(**raw)
    return config


def get_fw_release(repo=None) -> Path:  # pragma: no cover
    """
    Resolves the local firmware release archive.

    `repo` may point to the archive itself, to a release directory,
    or to a brewblox-firmware checkout.
    If unset, $BREWBLOX_FIRMWARE_REPO is used, and then `FW_LOCAL_REPO`.

    The archive is generated by `invoke deploy.local-release`
    in the brewblox-firmware repository.
    """
    path = Path(repo or os.getenv('BREWBLOX_FIRMWARE_REPO') or FW_LOCAL_REPO).expanduser()

    if path.is_file():
        return path.resolve()

    for candidate in [path / FW_RELEASE_FILE, path / 'release' / FW_RELEASE_FILE]:
        if candidate.is_file():
            return candidate.resolve()

    raise Exit(
        f'No {FW_RELEASE_FILE} found in "{path}". '
        'Run `invoke deploy.local-release` in the brewblox-firmware repository, '
        'or point --repo / $BREWBLOX_FIRMWARE_REPO at its location.'
    )


def get_fw_proto_dir(release: Path) -> Path | None:  # pragma: no cover
    """
    Finds the brewblox-proto submodule belonging to the brewblox-firmware
    checkout that generated `release`.
    Returns None if the submodule is not initialized.
    """
    for parent in release.parents:
        candidate = parent / FW_PROTO_SUBMODULE
        if (candidate / '.git').exists():
            return candidate
    return None


def checkout_proto(ctx: Context, proto_sha: str, source: Path | None = None):  # pragma: no cover
    """
    Checks out `proto_sha` in the brewblox-proto submodule.
    Objects are fetched from `source` if set, and from the remote otherwise.
    """
    with ctx.cd(ROOT / 'brewblox-proto'):
        # Fetching is skipped if the commit is already available locally
        known = ctx.run(f'git cat-file -e "{proto_sha}^{{commit}}"', warn=True, hide=True).ok
        if not known:
            ctx.run(f'git fetch --quiet "{source}"' if source else 'git fetch')
        ctx.run(f'git checkout --quiet "{proto_sha}"')


@task
def compile_proto(ctx: Context):
    out_dir = ROOT / 'brewblox_devcon_spark/codec/proto-compiled'

    with ctx.cd(ROOT):
        ctx.run('uv sync')
        ctx.run(f'rm -rf {out_dir}/*_pb2.py')
        ctx.run(
            ' '.join(
                [
                    'python3 -m grpc_tools.protoc',
                    '-I=./brewblox-proto/proto',
                    f'--python_out="{out_dir}"',
                    ' ./brewblox-proto/proto/**.proto',
                ]
            )
        )


@task
def download_firmware(ctx: Context):
    fw_config = get_fw_config()
    fw_dir = ROOT / 'firmware'

    fw_date = fw_config.firmware_date
    fw_version = fw_config.firmware_version
    fw_file = 'brewblox-release.tar.gz'
    url = f'{FW_BASE_URL}/{fw_date}-{fw_version}/{fw_file}'
    print(f'Downloading firmware release {fw_date}-{fw_version}')

    with ctx.cd(ROOT):
        # Clear firmware dir
        ctx.run(f'mkdir -p {fw_dir}')
        ctx.run(f'rm -rf {fw_dir}/*')

        # Download and extract firmware files
        ctx.run(f'curl -sSfO "{url}"')
        ctx.run(f'tar -xzvf {fw_file} -C {fw_dir}')
        ctx.run(f'rm {fw_file}')

        # Simulators are executable files
        ctx.run(f'chmod +x {fw_dir}/*.sim')


@task
def fetch_firmware(ctx: Context, repo=None):
    """
    Extracts firmware files from a local brewblox-firmware release archive.

    This is the offline counterpart to `download-firmware`:
    instead of downloading a release from blob storage,
    it reads the archive generated by `invoke deploy.local-release`.

    As the archive includes the firmware.ini for that build,
    the firmware.ini in this repository is overwritten.
    """
    release = get_fw_release(repo)
    fw_dir = ROOT / 'firmware'

    print(f'Extracting firmware release from {release}')

    with ctx.cd(ROOT):
        # Clear firmware dir
        ctx.run(f'mkdir -p {fw_dir}')
        ctx.run(f'rm -rf {fw_dir}/*')

        # Extract firmware files
        ctx.run(f'tar -xzf "{release}" -C {fw_dir}')

        # The archive includes the firmware.ini describing this build
        if not (fw_dir / 'firmware.ini').is_file():
            raise Exit(f'No firmware.ini found in "{release}"')
        ctx.run(f'cp {fw_dir}/firmware.ini {ROOT}/firmware.ini')

        # Simulators are executable files.
        # Local releases may not include them if only some platforms were built.
        if list(fw_dir.glob('*.sim')):
            ctx.run(f'chmod +x {fw_dir}/*.sim')
        else:
            print('WARNING: this release includes no simulator binaries.')
            print('WARNING: integration tests will not be able to run.')

    fw_config = get_fw_config()
    print(f'Fetched firmware release {fw_config.firmware_date}-{fw_config.firmware_version}')


@task
def update_firmware(ctx: Context, release='develop', local=False, repo=None):
    """
    Updates firmware.ini, the brewblox-proto submodule, and the firmware/ directory.

    By default, the release is downloaded from blob storage.
    If --local or --repo is set, a local brewblox-firmware release is used,
    and nothing is downloaded.
    """
    local = local or bool(repo)
    proto_source = None

    if local:
        fetch_firmware(ctx, repo)
        proto_source = get_fw_proto_dir(get_fw_release(repo))
    else:
        url = f'{FW_BASE_URL}/{release}/firmware.ini'
        print(url)

        with ctx.cd(ROOT):
            ctx.run(f'curl -sSf -o firmware.ini "{url}"')

    fw_config = get_fw_config()
    fw_date = fw_config.firmware_date
    fw_version = fw_config.firmware_version
    proto_sha = fw_config.proto_sha

    print(f'Updating to firmware release {fw_date}-{fw_version}')

    checkout_proto(ctx, proto_sha, proto_source)
    compile_proto(ctx)

    if not local:
        download_firmware(ctx)


@task
def testclean(ctx: Context):
    """
    Cleans up leftover test containers, networks, and simulators.
    Container cleanup is normally done in test fixtures.
    This is skipped if debugged tests are stopped halfway.
    """
    result = ctx.run('docker ps -aq --filter "name=pytest"', hide='stdout')
    containers = result.stdout.strip().replace('\n', ' ')
    if containers:
        ctx.run(f'docker rm -f {containers}')
    ctx.run('docker network prune -f')

    with suppress(UnexpectedExit):
        # returns 1 if nothing killed
        ctx.run('sudo pkill -ef -9 brewblox-amd64.sim')


@task()
def image(ctx: Context, tag='local'):
    with ctx.cd(ROOT):
        ctx.run(f'docker build --load -t ghcr.io/brewblox/brewblox-devcon-spark:{tag} -f Dockerfile.service .')


@task()
def buildx(ctx: Context, tag='local', platform='linux/amd64,linux/arm/v7,linux/arm64/v8'):
    with ctx.cd(ROOT):
        ctx.run(
            f'docker buildx build --no-cache --platform {platform} -t ghcr.io/brewblox/brewblox-devcon-spark:{tag} -f Dockerfile.service .'
        )


@task
def fetch_build(ctx: Context, tag='local', repo=None):
    """
    Builds a service image from a local brewblox-firmware release.

    This combines `update-firmware --local` and `image`.
    Nothing is downloaded: firmware.ini, the firmware binaries,
    and the .proto files all come from a local brewblox-firmware checkout.
    """
    update_firmware(ctx, local=True, repo=repo)
    image(ctx, tag)
    print(f'Build complete: ghcr.io/brewblox/brewblox-devcon-spark:{tag}')


@task()
def flasher_image(ctx: Context, tag='local'):
    with ctx.cd(ROOT):
        ctx.run(f'docker build --load -t ghcr.io/brewblox/brewblox-firmware-flasher:{tag} -f Dockerfile.flasher .')


@task()
def flasher_buildx(ctx: Context, tag='local', platform='linux/amd64,linux/arm/v7,linux/arm64/v8'):
    with ctx.cd(ROOT):
        ctx.run(
            f'docker buildx build --no-cache --platform {platform} -t ghcr.io/brewblox/brewblox-firmware-flasher:{tag} -f Dockerfile.flasher .'
        )
