# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DisplaySettings.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import brewblox_pb2 as brewblox__pb2
import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x44isplaySettings.proto\x12\x14\x62lox.DisplaySettings\x1a\x0e\x62rewblox.proto\x1a\x0cnanopb.proto\"\xf2\x01\n\x06Widget\x12\x12\n\x03pos\x18\x01 \x01(\rB\x05\x92?\x02\x38\x08\x12\x1f\n\x05\x63olor\x18\x02 \x01(\x0c\x42\x10\x92?\x02\x08\x03\x92?\x02x\x01\x8a\xb5\x18\x02\x38\x01\x12\x13\n\x04name\x18\x03 \x01(\tB\x05\x92?\x02\x08\x10\x12!\n\ntempSensor\x18\n \x01(\rB\x0b\x8a\xb5\x18\x02\x18\x02\x92?\x02\x38\x10H\x00\x12)\n\x12setpointSensorPair\x18\x0b \x01(\rB\x0b\x8a\xb5\x18\x02\x18\x04\x92?\x02\x38\x10H\x00\x12%\n\x0e\x61\x63tuatorAnalog\x18\x0c \x01(\rB\x0b\x8a\xb5\x18\x02\x18\x05\x92?\x02\x38\x10H\x00\x12\x1b\n\x03pid\x18\x0e \x01(\rB\x0c\x8a\xb5\x18\x03\x18\xb0\x02\x92?\x02\x38\x10H\x00\x42\x0c\n\nWidgetType\"\xba\x01\n\x05\x42lock\x12\x34\n\x07widgets\x18\x01 \x03(\x0b\x32\x1c.blox.DisplaySettings.WidgetB\x05\x92?\x02\x10\x06\x12\x13\n\x04name\x18\x02 \x01(\tB\x05\x92?\x02\x08(\x12\x1f\n\nbrightness\x18Z \x01(\x08\x42\x0b\x8a\xb5\x18\x02H\x01\x92?\x02\x18\x03\x12\x1d\n\x08timeZone\x18[ \x01(\x08\x42\x0b\x8a\xb5\x18\x02H\x01\x92?\x02\x18\x03\x12\x1d\n\x08tempUnit\x18\\ \x01(\x08\x42\x0b\x8a\xb5\x18\x02H\x01\x92?\x02\x18\x03:\x07\x8a\xb5\x18\x03\x18\xba\x02\x62\x06proto3')



_WIDGET = DESCRIPTOR.message_types_by_name['Widget']
_BLOCK = DESCRIPTOR.message_types_by_name['Block']
Widget = _reflection.GeneratedProtocolMessageType('Widget', (_message.Message,), {
  'DESCRIPTOR' : _WIDGET,
  '__module__' : 'DisplaySettings_pb2'
  # @@protoc_insertion_point(class_scope:blox.DisplaySettings.Widget)
  })
_sym_db.RegisterMessage(Widget)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), {
  'DESCRIPTOR' : _BLOCK,
  '__module__' : 'DisplaySettings_pb2'
  # @@protoc_insertion_point(class_scope:blox.DisplaySettings.Block)
  })
_sym_db.RegisterMessage(Block)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WIDGET.fields_by_name['pos']._options = None
  _WIDGET.fields_by_name['pos']._serialized_options = b'\222?\0028\010'
  _WIDGET.fields_by_name['color']._options = None
  _WIDGET.fields_by_name['color']._serialized_options = b'\222?\002\010\003\222?\002x\001\212\265\030\0028\001'
  _WIDGET.fields_by_name['name']._options = None
  _WIDGET.fields_by_name['name']._serialized_options = b'\222?\002\010\020'
  _WIDGET.fields_by_name['tempSensor']._options = None
  _WIDGET.fields_by_name['tempSensor']._serialized_options = b'\212\265\030\002\030\002\222?\0028\020'
  _WIDGET.fields_by_name['setpointSensorPair']._options = None
  _WIDGET.fields_by_name['setpointSensorPair']._serialized_options = b'\212\265\030\002\030\004\222?\0028\020'
  _WIDGET.fields_by_name['actuatorAnalog']._options = None
  _WIDGET.fields_by_name['actuatorAnalog']._serialized_options = b'\212\265\030\002\030\005\222?\0028\020'
  _WIDGET.fields_by_name['pid']._options = None
  _WIDGET.fields_by_name['pid']._serialized_options = b'\212\265\030\003\030\260\002\222?\0028\020'
  _BLOCK.fields_by_name['widgets']._options = None
  _BLOCK.fields_by_name['widgets']._serialized_options = b'\222?\002\020\006'
  _BLOCK.fields_by_name['name']._options = None
  _BLOCK.fields_by_name['name']._serialized_options = b'\222?\002\010('
  _BLOCK.fields_by_name['brightness']._options = None
  _BLOCK.fields_by_name['brightness']._serialized_options = b'\212\265\030\002H\001\222?\002\030\003'
  _BLOCK.fields_by_name['timeZone']._options = None
  _BLOCK.fields_by_name['timeZone']._serialized_options = b'\212\265\030\002H\001\222?\002\030\003'
  _BLOCK.fields_by_name['tempUnit']._options = None
  _BLOCK.fields_by_name['tempUnit']._serialized_options = b'\212\265\030\002H\001\222?\002\030\003'
  _BLOCK._options = None
  _BLOCK._serialized_options = b'\212\265\030\003\030\272\002'
  _WIDGET._serialized_start=78
  _WIDGET._serialized_end=320
  _BLOCK._serialized_start=323
  _BLOCK._serialized_end=509
# @@protoc_insertion_point(module_scope)
