# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DS2413.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import brewblox_pb2 as brewblox__pb2
import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DS2413.proto',
  package='blox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x44S2413.proto\x12\x04\x62lox\x1a\x0e\x62rewblox.proto\x1a\x0cnanopb.proto\"F\n\x06\x44S2413\x12\x17\n\x07\x61\x64\x64ress\x18\x01 \x01(\x06\x42\x06\x8a\xb5\x18\x02 \x01\x12\x1a\n\x05state\x18\x02 \x01(\rB\x0b\x8a\xb5\x18\x02(\x01\x92?\x02\x38\x08:\x07\x8a\xb5\x18\x03\x18\xbb\x02\x62\x06proto3')
  ,
  dependencies=[brewblox__pb2.DESCRIPTOR,nanopb__pb2.DESCRIPTOR,])




_DS2413 = _descriptor.Descriptor(
  name='DS2413',
  full_name='blox.DS2413',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='blox.DS2413.address', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\212\265\030\002 \001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='blox.DS2413.state', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\212\265\030\002(\001\222?\0028\010'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\212\265\030\003\030\273\002'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=122,
)

DESCRIPTOR.message_types_by_name['DS2413'] = _DS2413
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DS2413 = _reflection.GeneratedProtocolMessageType('DS2413', (_message.Message,), dict(
  DESCRIPTOR = _DS2413,
  __module__ = 'DS2413_pb2'
  # @@protoc_insertion_point(class_scope:blox.DS2413)
  ))
_sym_db.RegisterMessage(DS2413)


_DS2413.fields_by_name['address']._options = None
_DS2413.fields_by_name['state']._options = None
_DS2413._options = None
# @@protoc_insertion_point(module_scope)
