# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MockPins.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import brewblox_pb2 as brewblox__pb2
import nanopb_pb2 as nanopb__pb2
import IoArray_pb2 as IoArray__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='MockPins.proto',
  package='blox',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eMockPins.proto\x12\x04\x62lox\x1a\x0e\x62rewblox.proto\x1a\x0cnanopb.proto\x1a\rIoArray.proto\"i\n\x08MockPins\x12\x33\n\x08\x63hannels\x18\x02 \x03(\x0b\x32\x0f.blox.IoChannelB\x10\x92?\x02\x10\x08\x92?\x02x\x01\x8a\xb5\x18\x02(\x01\x12\x19\n\x04pins\x18Z \x01(\x08\x42\x0b\x8a\xb5\x18\x02H\x01\x92?\x02\x18\x03:\r\x8a\xb5\x18\x03\x18\xc3\x02\x8a\xb5\x18\x02H\n*\xd4\x01\n\x12MockPinsChannelIds\x12\x16\n\x12MOCKPINS_CHAN_NONE\x10\x00\x12\x13\n\x0fMOCKPINS_CHAN_A\x10\x01\x12\x13\n\x0fMOCKPINS_CHAN_B\x10\x02\x12\x13\n\x0fMOCKPINS_CHAN_C\x10\x03\x12\x13\n\x0fMOCKPINS_CHAN_D\x10\x04\x12\x13\n\x0fMOCKPINS_CHAN_E\x10\x05\x12\x13\n\x0fMOCKPINS_CHAN_F\x10\x06\x12\x13\n\x0fMOCKPINS_CHAN_G\x10\x07\x12\x13\n\x0fMOCKPINS_CHAN_H\x10\x08\x62\x06proto3'
  ,
  dependencies=[brewblox__pb2.DESCRIPTOR,nanopb__pb2.DESCRIPTOR,IoArray__pb2.DESCRIPTOR,])

_MOCKPINSCHANNELIDS = _descriptor.EnumDescriptor(
  name='MockPinsChannelIds',
  full_name='blox.MockPinsChannelIds',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MOCKPINS_CHAN_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOCKPINS_CHAN_A', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOCKPINS_CHAN_B', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOCKPINS_CHAN_C', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOCKPINS_CHAN_D', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOCKPINS_CHAN_E', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOCKPINS_CHAN_F', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOCKPINS_CHAN_G', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOCKPINS_CHAN_H', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=177,
  serialized_end=389,
)
_sym_db.RegisterEnumDescriptor(_MOCKPINSCHANNELIDS)

MockPinsChannelIds = enum_type_wrapper.EnumTypeWrapper(_MOCKPINSCHANNELIDS)
MOCKPINS_CHAN_NONE = 0
MOCKPINS_CHAN_A = 1
MOCKPINS_CHAN_B = 2
MOCKPINS_CHAN_C = 3
MOCKPINS_CHAN_D = 4
MOCKPINS_CHAN_E = 5
MOCKPINS_CHAN_F = 6
MOCKPINS_CHAN_G = 7
MOCKPINS_CHAN_H = 8



_MOCKPINS = _descriptor.Descriptor(
  name='MockPins',
  full_name='blox.MockPins',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='channels', full_name='blox.MockPins.channels', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\002\020\010\222?\002x\001\212\265\030\002(\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pins', full_name='blox.MockPins.pins', index=1,
      number=90, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\212\265\030\002H\001\222?\002\030\003', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\212\265\030\003\030\303\002\212\265\030\002H\n',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=174,
)

_MOCKPINS.fields_by_name['channels'].message_type = IoArray__pb2._IOCHANNEL
DESCRIPTOR.message_types_by_name['MockPins'] = _MOCKPINS
DESCRIPTOR.enum_types_by_name['MockPinsChannelIds'] = _MOCKPINSCHANNELIDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MockPins = _reflection.GeneratedProtocolMessageType('MockPins', (_message.Message,), {
  'DESCRIPTOR' : _MOCKPINS,
  '__module__' : 'MockPins_pb2'
  # @@protoc_insertion_point(class_scope:blox.MockPins)
  })
_sym_db.RegisterMessage(MockPins)


_MOCKPINS.fields_by_name['channels']._options = None
_MOCKPINS.fields_by_name['pins']._options = None
_MOCKPINS._options = None
# @@protoc_insertion_point(module_scope)
