# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OneWireGpioModule.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import brewblox_pb2 as brewblox__pb2
import nanopb_pb2 as nanopb__pb2
import IoArray_pb2 as IoArray__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='OneWireGpioModule.proto',
  package='blox',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17OneWireGpioModule.proto\x12\x04\x62lox\x1a\x0e\x62rewblox.proto\x1a\x0cnanopb.proto\x1a\rIoArray.proto\"\xaa\x01\n\x0bGpioChannel\x12\x11\n\x02id\x18\x01 \x01(\rB\x05\x92?\x02\x38\x08\x12#\n\x06\x63onfig\x18\x02 \x01(\x0e\x32\x13.blox.ChannelConfig\x12\x13\n\x04pins\x18\x03 \x01(\rB\x05\x92?\x02\x38\x10\x12\x19\n\nwhenActive\x18\x04 \x01(\rB\x05\x92?\x02\x38\x10\x12\x1b\n\x0cwhenInactive\x18\x05 \x01(\rB\x05\x92?\x02\x38\x10\x12\x16\n\x07pwmDuty\x18\x06 \x01(\rB\x05\x92?\x02\x38\x08\"\xed\x01\n\x11OneWireGpioModule\x12*\n\x08\x63hannels\x18\x01 \x03(\x0b\x32\x11.blox.GpioChannelB\x05\x92?\x02\x10\x08\x12\x1d\n\x0emodulePosition\x18\x02 \x01(\rB\x05\x92?\x02\x38\x08\x12\x1b\n\x06status\x18\x03 \x01(\rB\x0b\x8a\xb5\x18\x02(\x01\x92?\x02\x38\x08\x12\x1a\n\x05\x64rive\x18\x04 \x01(\rB\x0b\x8a\xb5\x18\x02(\x01\x92?\x02\x38\x10\x12 \n\x0boverCurrent\x18\x05 \x01(\rB\x0b\x8a\xb5\x18\x02(\x01\x92?\x02\x38\x10\x12\x1d\n\x08openLoad\x18\x06 \x01(\rB\x0b\x8a\xb5\x18\x02(\x01\x92?\x02\x38\x10:\x13\x8a\xb5\x18\x03\x18\xc5\x02\x8a\xb5\x18\x02H\n\x8a\xb5\x18\x02H\x0c\x62\x06proto3'
  ,
  dependencies=[brewblox__pb2.DESCRIPTOR,nanopb__pb2.DESCRIPTOR,IoArray__pb2.DESCRIPTOR,])




_GPIOCHANNEL = _descriptor.Descriptor(
  name='GpioChannel',
  full_name='blox.GpioChannel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='blox.GpioChannel.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\010', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config', full_name='blox.GpioChannel.config', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pins', full_name='blox.GpioChannel.pins', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\020', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='whenActive', full_name='blox.GpioChannel.whenActive', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\020', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='whenInactive', full_name='blox.GpioChannel.whenInactive', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\020', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pwmDuty', full_name='blox.GpioChannel.pwmDuty', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\010', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=249,
)


_ONEWIREGPIOMODULE = _descriptor.Descriptor(
  name='OneWireGpioModule',
  full_name='blox.OneWireGpioModule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='channels', full_name='blox.OneWireGpioModule.channels', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\002\020\010', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='modulePosition', full_name='blox.OneWireGpioModule.modulePosition', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\010', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='blox.OneWireGpioModule.status', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\212\265\030\002(\001\222?\0028\010', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drive', full_name='blox.OneWireGpioModule.drive', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\212\265\030\002(\001\222?\0028\020', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='overCurrent', full_name='blox.OneWireGpioModule.overCurrent', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\212\265\030\002(\001\222?\0028\020', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='openLoad', full_name='blox.OneWireGpioModule.openLoad', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\212\265\030\002(\001\222?\0028\020', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\212\265\030\003\030\305\002\212\265\030\002H\n\212\265\030\002H\014',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=489,
)

_GPIOCHANNEL.fields_by_name['config'].enum_type = IoArray__pb2._CHANNELCONFIG
_ONEWIREGPIOMODULE.fields_by_name['channels'].message_type = _GPIOCHANNEL
DESCRIPTOR.message_types_by_name['GpioChannel'] = _GPIOCHANNEL
DESCRIPTOR.message_types_by_name['OneWireGpioModule'] = _ONEWIREGPIOMODULE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GpioChannel = _reflection.GeneratedProtocolMessageType('GpioChannel', (_message.Message,), {
  'DESCRIPTOR' : _GPIOCHANNEL,
  '__module__' : 'OneWireGpioModule_pb2'
  # @@protoc_insertion_point(class_scope:blox.GpioChannel)
  })
_sym_db.RegisterMessage(GpioChannel)

OneWireGpioModule = _reflection.GeneratedProtocolMessageType('OneWireGpioModule', (_message.Message,), {
  'DESCRIPTOR' : _ONEWIREGPIOMODULE,
  '__module__' : 'OneWireGpioModule_pb2'
  # @@protoc_insertion_point(class_scope:blox.OneWireGpioModule)
  })
_sym_db.RegisterMessage(OneWireGpioModule)


_GPIOCHANNEL.fields_by_name['id']._options = None
_GPIOCHANNEL.fields_by_name['pins']._options = None
_GPIOCHANNEL.fields_by_name['whenActive']._options = None
_GPIOCHANNEL.fields_by_name['whenInactive']._options = None
_GPIOCHANNEL.fields_by_name['pwmDuty']._options = None
_ONEWIREGPIOMODULE.fields_by_name['channels']._options = None
_ONEWIREGPIOMODULE.fields_by_name['modulePosition']._options = None
_ONEWIREGPIOMODULE.fields_by_name['status']._options = None
_ONEWIREGPIOMODULE.fields_by_name['drive']._options = None
_ONEWIREGPIOMODULE.fields_by_name['overCurrent']._options = None
_ONEWIREGPIOMODULE.fields_by_name['openLoad']._options = None
_ONEWIREGPIOMODULE._options = None
# @@protoc_insertion_point(module_scope)
