# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TempSensorCombi.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import brewblox_pb2 as brewblox__pb2
import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15TempSensorCombi.proto\x12\x14\x62lox.TempSensorCombi\x1a\x0e\x62rewblox.proto\x1a\x0cnanopb.proto\"\xa4\x01\n\x05\x42lock\x12-\n\x05value\x18\x01 \x01(\x11\x42\x1e\x8a\xb5\x18\x02\x30\x01\x8a\xb5\x18\x02\x08\x01\x8a\xb5\x18\x03\x10\x80 \x8a\xb5\x18\x02(\x01\x92?\x02\x38 \x12:\n\x0b\x63ombineFunc\x18\x02 \x01(\x0e\x32%.blox.TempSensorCombi.SensorCombiFunc\x12!\n\x07sensors\x18\x03 \x03(\rB\x10\x8a\xb5\x18\x02\x18\x02\x92?\x02\x38\x10\x92?\x02\x10\x08:\r\x8a\xb5\x18\x03\x18\xc4\x02\x8a\xb5\x18\x02H\x02*b\n\x0fSensorCombiFunc\x12\x19\n\x15SENSOR_COMBI_FUNC_AVG\x10\x00\x12\x19\n\x15SENSOR_COMBI_FUNC_MIN\x10\x01\x12\x19\n\x15SENSOR_COMBI_FUNC_MAX\x10\x02\x62\x06proto3')

_SENSORCOMBIFUNC = DESCRIPTOR.enum_types_by_name['SensorCombiFunc']
SensorCombiFunc = enum_type_wrapper.EnumTypeWrapper(_SENSORCOMBIFUNC)
SENSOR_COMBI_FUNC_AVG = 0
SENSOR_COMBI_FUNC_MIN = 1
SENSOR_COMBI_FUNC_MAX = 2


_BLOCK = DESCRIPTOR.message_types_by_name['Block']
Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), {
  'DESCRIPTOR' : _BLOCK,
  '__module__' : 'TempSensorCombi_pb2'
  # @@protoc_insertion_point(class_scope:blox.TempSensorCombi.Block)
  })
_sym_db.RegisterMessage(Block)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BLOCK.fields_by_name['value']._options = None
  _BLOCK.fields_by_name['value']._serialized_options = b'\212\265\030\0020\001\212\265\030\002\010\001\212\265\030\003\020\200 \212\265\030\002(\001\222?\0028 '
  _BLOCK.fields_by_name['sensors']._options = None
  _BLOCK.fields_by_name['sensors']._serialized_options = b'\212\265\030\002\030\002\222?\0028\020\222?\002\020\010'
  _BLOCK._options = None
  _BLOCK._serialized_options = b'\212\265\030\003\030\304\002\212\265\030\002H\002'
  _SENSORCOMBIFUNC._serialized_start=244
  _SENSORCOMBIFUNC._serialized_end=342
  _BLOCK._serialized_start=78
  _BLOCK._serialized_end=242
# @@protoc_insertion_point(module_scope)
