# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TempSensorExternal.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'TempSensorExternal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import brewblox_pb2 as brewblox__pb2
import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18TempSensorExternal.proto\x12\x17\x62lox.TempSensorExternal\x1a\x0e\x62rewblox.proto\x1a\x0cnanopb.proto\"\xfa\x01\n\x05\x42lock\x12\x1c\n\x07\x65nabled\x18\x01 \x01(\x08\x42\x06\x8a\xb5\x18\x02x\x01H\x00\x88\x01\x01\x12#\n\x07timeout\x18\x02 \x01(\rB\r\x92?\x02\x38 \x8a\xb5\x18\x04\x08\x03x\x01H\x01\x88\x01\x01\x12$\n\x07setting\x18\x03 \x01(\x11\x42\x0e\x92?\x02\x38 \x8a\xb5\x18\x05\x08\x01\x10\x80 H\x02\x88\x01\x01\x12\"\n\x0blastUpdated\x18\x04 \x01(\rB\r\x92?\x02\x38 \x8a\xb5\x18\x04(\x01X\x01\x12)\n\x05value\x18\x05 \x01(\x11\x42\x15\x92?\x02\x38 \x8a\xb5\x18\x0c\x08\x01\x10\x80 (\x01\x30\x01\x88\x01\x03H\x03\x88\x01\x01:\x0b\x8a\xb5\x18\x07\x18\xc8\x02J\x02\x02\x0f\x42\n\n\x08_enabledB\n\n\x08_timeoutB\n\n\x08_settingB\x08\n\x06_valueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TempSensorExternal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLOCK'].fields_by_name['enabled']._loaded_options = None
  _globals['_BLOCK'].fields_by_name['enabled']._serialized_options = b'\212\265\030\002x\001'
  _globals['_BLOCK'].fields_by_name['timeout']._loaded_options = None
  _globals['_BLOCK'].fields_by_name['timeout']._serialized_options = b'\222?\0028 \212\265\030\004\010\003x\001'
  _globals['_BLOCK'].fields_by_name['setting']._loaded_options = None
  _globals['_BLOCK'].fields_by_name['setting']._serialized_options = b'\222?\0028 \212\265\030\005\010\001\020\200 '
  _globals['_BLOCK'].fields_by_name['lastUpdated']._loaded_options = None
  _globals['_BLOCK'].fields_by_name['lastUpdated']._serialized_options = b'\222?\0028 \212\265\030\004(\001X\001'
  _globals['_BLOCK'].fields_by_name['value']._loaded_options = None
  _globals['_BLOCK'].fields_by_name['value']._serialized_options = b'\222?\0028 \212\265\030\014\010\001\020\200 (\0010\001\210\001\003'
  _globals['_BLOCK']._loaded_options = None
  _globals['_BLOCK']._serialized_options = b'\212\265\030\007\030\310\002J\002\002\017'
  _globals['_BLOCK']._serialized_start=84
  _globals['_BLOCK']._serialized_end=334
# @@protoc_insertion_point(module_scope)
