# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TouchSettings.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import brewblox_pb2 as brewblox__pb2
import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13TouchSettings.proto\x12\x12\x62lox.TouchSettings\x1a\x0e\x62rewblox.proto\x1a\x0cnanopb.proto\"\xb6\x01\n\x05\x42lock\x12\x32\n\ncalibrated\x18\x01 \x01(\x0e\x32\x1e.blox.TouchSettings.Calibrated\x12\x16\n\x07xOffset\x18\x02 \x01(\x05\x42\x05\x92?\x02\x38\x10\x12\x16\n\x07yOffset\x18\x03 \x01(\x05\x42\x05\x92?\x02\x38\x10\x12\x1f\n\x10xBitsPerPixelX16\x18\x04 \x01(\rB\x05\x92?\x02\x38\x10\x12\x1f\n\x10yBitsPerPixelX16\x18\x05 \x01(\rB\x05\x92?\x02\x38\x10:\x07\x8a\xb5\x18\x03\x18\xb9\x02*G\n\nCalibrated\x12\x11\n\rCALIBRATED_NO\x10\x00\x12\x12\n\x0e\x43\x41LIBRATED_YES\x10\x01\x12\x12\n\x0e\x43\x41LIBRATED_NEW\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TouchSettings_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _BLOCK.fields_by_name['xOffset']._options = None
  _BLOCK.fields_by_name['xOffset']._serialized_options = b'\222?\0028\020'
  _BLOCK.fields_by_name['yOffset']._options = None
  _BLOCK.fields_by_name['yOffset']._serialized_options = b'\222?\0028\020'
  _BLOCK.fields_by_name['xBitsPerPixelX16']._options = None
  _BLOCK.fields_by_name['xBitsPerPixelX16']._serialized_options = b'\222?\0028\020'
  _BLOCK.fields_by_name['yBitsPerPixelX16']._options = None
  _BLOCK.fields_by_name['yBitsPerPixelX16']._serialized_options = b'\222?\0028\020'
  _BLOCK._options = None
  _BLOCK._serialized_options = b'\212\265\030\003\030\271\002'
  _globals['_CALIBRATED']._serialized_start=258
  _globals['_CALIBRATED']._serialized_end=329
  _globals['_BLOCK']._serialized_start=74
  _globals['_BLOCK']._serialized_end=256
# @@protoc_insertion_point(module_scope)
