# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VolumeSensor.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import brewblox_pb2 as brewblox__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12VolumeSensor.proto\x12\x11\x62lox.VolumeSensor\x1a\x0e\x62rewblox.proto\"\xfc\x01\n\x05\x42lock\x12!\n\x0epressureDevice\x18\x01 \x01(\rB\t\x8a\xb5\x18\x05\x18\xce\x02x\x01\x12%\n\x12zeroPressureVolume\x18\x03 \x01(\x11\x42\t\x8a\xb5\x18\x05\x10\x80\x08x\x01\x12 \n\rheightPerMbar\x18\x04 \x01(\x11\x42\t\x8a\xb5\x18\x05\x10\x80 x\x01\x12\x1a\n\x07mlPerMm\x18\x05 \x01(\x11\x42\t\x8a\xb5\x18\x05\x10\x80 x\x01\x12\x1f\n\x0csensorHeight\x18\x06 \x01(\x11\x42\t\x8a\xb5\x18\x05\x10\x80\x08x\x01\x12\x1b\n\x06volume\x18\t \x01(\x11\x42\x0b\x8a\xb5\x18\x07\x10\x80\x08(\x01\x30\x01\x12\x1b\n\x06height\x18\n \x01(\x11\x42\x0b\x8a\xb5\x18\x07\x10\x80\x08(\x01\x30\x01:\n\x8a\xb5\x18\x06\x18\xcf\x02J\x01\x1fJ\x04\x08\x02\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'VolumeSensor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BLOCK'].fields_by_name['pressureDevice']._options = None
  _globals['_BLOCK'].fields_by_name['pressureDevice']._serialized_options = b'\212\265\030\005\030\316\002x\001'
  _globals['_BLOCK'].fields_by_name['zeroPressureVolume']._options = None
  _globals['_BLOCK'].fields_by_name['zeroPressureVolume']._serialized_options = b'\212\265\030\005\020\200\010x\001'
  _globals['_BLOCK'].fields_by_name['heightPerMbar']._options = None
  _globals['_BLOCK'].fields_by_name['heightPerMbar']._serialized_options = b'\212\265\030\005\020\200 x\001'
  _globals['_BLOCK'].fields_by_name['mlPerMm']._options = None
  _globals['_BLOCK'].fields_by_name['mlPerMm']._serialized_options = b'\212\265\030\005\020\200 x\001'
  _globals['_BLOCK'].fields_by_name['sensorHeight']._options = None
  _globals['_BLOCK'].fields_by_name['sensorHeight']._serialized_options = b'\212\265\030\005\020\200\010x\001'
  _globals['_BLOCK'].fields_by_name['volume']._options = None
  _globals['_BLOCK'].fields_by_name['volume']._serialized_options = b'\212\265\030\007\020\200\010(\0010\001'
  _globals['_BLOCK'].fields_by_name['height']._options = None
  _globals['_BLOCK'].fields_by_name['height']._serialized_options = b'\212\265\030\007\020\200\010(\0010\001'
  _globals['_BLOCK']._options = None
  _globals['_BLOCK']._serialized_options = b'\212\265\030\006\030\317\002J\001\037'
  _globals['_BLOCK']._serialized_start=58
  _globals['_BLOCK']._serialized_end=310
# @@protoc_insertion_point(module_scope)
