#! /usr/bin/env bash
set -ex

function do_inspect() {
    bin="$1"
    res="$(particle binary inspect ./"${bin}")"
    echo "$res"
    grep -q "CRC is ok" <<< "$res"

    echo "Checking compile target..."
    if grep -q "photon" <<< "$bin"; then
        grep -q "Compiled for photon" <<< "$res"
    else
        grep -q "Compiled for p1" <<< "$res"
    fi
}

do_inspect brewblox-p1.bin
do_inspect brewblox-photon.bin
