name: CI build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [develop, edge]

jobs:
  build:
    if: github.repository_owner == 'BrewBlox'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry wheel
          poetry install

      - name: Download firmware
        run: |
          bash dev/download-firmware.sh

      - name: Test
        run: |
          poetry run pytest
          poetry run flake8

      - name: Enable multiplatform Docker build
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: ghcr.io login
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: (Service) Run setup script
        run: |
          bash docker/before_build.sh

      - name: (Service) Image metadata
        id: service_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/brewblox/brewblox-devcon-spark

      - name: (Service) Build Docker image
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.service_meta.outputs.tags }}
          labels: ${{ steps.service_meta.outputs.labels }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          context: docker

      - name: (Flasher) Run setup script
        run: |
          bash flasher/before_build.sh

      - name: (Flasher) Image metadata
        id: flasher_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/brewblox/brewblox-firmware-flasher

      - name: (Flasher) Build Docker image
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.flasher_meta.outputs.tags }}
          labels: ${{ steps.flasher_meta.outputs.labels }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          context: flasher
